### ISSUE TITLE
[Feature Request] Integration with MJE (Even on Commission)

### ISSUE THREAD

**Issue by p4535992** [eXaminator/kanka-foundry#116]
You have done a beautiful job with the journals, but unfortunately I have to synchronize with the journals of [MJE](https://github.com/ironmonk88/monks-enhanced-journal) (I personally find yours a bit nicer, but that's not my decision).

I would need then that in the import phase (with a separate settings module probably) instead of setting the flags and types of your enities to instead set the flags and types of MJE .

The correlation between your flags and types is very similar, so from a technical point of view it would be a matter of preparing a "mapping" code for flags and types (even those that are very similar).

If this is something you would be willing to consider I can try to open a PR about it.

I am also willing to consider a commission for this (i really need this...) if you are willing to spend time on it.

**Comment by eXaminator** [comment]
Hey, I'll have to look into this before I make any promises. I'll put some time aside for this module sometime in the next few weeks as I'll test some upcoming kanka changes, but it probably won't be within the next 2 weeks or so. Maybe sometime in the second half of september or early october.

After that I can give you some feedback whether I think this seems feasible or not.

I have actually been tinkering with a completely sheet layout (which would use the foundry page system and thus would be closer to vanilla foundry in many ways), so the sheets of this module will probably change at some time anyway (if I ever get to actually completing that...) - mainly so that it is closer to vanilla and it hopefully is easier to style properly with theme modules etc. That being said, it might not be too far fetched to also allow MEJ to work with this, though I do see some potential points of irritation (like the fact that I'd have to see if I can make those entries read only or at least make sure people understand that their local changes cannot be synced back to Kanka and will be overridden by the next import of that entity). But like I said, I'll think about it, but it won't be a quick fix.

**Comment by eXaminator** [comment]
This is not something I'm likely to pursue in the foreseeable future, thus I'll close the issue now.
