### ISSUE TITLE
New Kanka journal options?

### ISSUE THREAD

**Issue by Nedrapter** [eXaminator/kanka-foundry#127]
So I'm noticing when I create a new journal there are some new Kanka related options. I attempted to create one to experiment and I got those errors in the console and the journal was just a normal empty journal.
![image](https://github.com/eXaminator/kanka-foundry/assets/74311190/2c9f8393-5b69-43c7-baa4-f6bb902454b0)

![image](https://github.com/eXaminator/kanka-foundry/assets/74311190/f045b625-42f4-44a5-84de-e213cb89bb64)
What exactly are these new options supposed to do? All of them give similar errors like the above when I try to create them and open a normal empty journal page.

**Comment by eXaminator** [comment]
I changed the journals to use the "new" page system of foundry instead of a completely custom layout. For that to work I have to register my custom page sheets. Sky, this also makes the available for users to select when creating their own journals. But that doesn't work, because your custom page does not have the necessary data model and I don't provide forms to edit them (because that's not what they are meant for).

Ideally foundry would allow me to hide these pages. Maybe I'll investigate a way to do that manually to reduce confusion, albeit at the price of potentially breaking interoperability with some other modules. At the very least I could at something like "don't use" to the names and add an info to the readme.

I think I should also open a foundry issue for that.

**Comment by Nedrapter** [comment]
Understood. Yea I was bit confused with all these new options.
