### ISSUE TITLE
Show note links.

### ISSUE THREAD

**Issue by SesuUisu** [eXaminator/kanka-foundry#131]
You can add links to the "note" field with `<code>[organisation:5115075]</code>` in Kanka. That will be added to Foundry as `[organisation:5115075]` instead of the internal Foundry Journal link like the rest.

**Comment by eXaminator** [comment]
This does work for me. Does Kanka correctly transform the link when you save it in Kanka? Because this module does not parse the syntax you mentioned above but the generated HTML code that Kanka produces based on this.

**Comment by SesuUisu** [comment]
![image](https://github.com/eXaminator/kanka-foundry/assets/5831548/b8d46e5b-0af7-4231-974d-5f3c8308d28c)
From left to right: Foundry, parsed note, entry field for attributes with code-tags

Other parsed links will work, but not those fields that can only parse when <code>-tags are needed (e.g. attribute fields). 
It seems that Kanka-Foundry module doesn't receive the parsed text but only the data within the tags.

**Comment by eXaminator** [comment]
I see, I misunderstood and didn't recognized that you meant the personality traits etc. I contacted the Kanka author and will see if he can add the parsed content for those traits so that I don't have to build some special cases for this, because I wouldn't be able to resolve those links unless the linked to entity was also synced.

**Comment by ilestis** [comment]
Traits now contain an `entry_parsed` property ;-) https://app.kanka.io/api-docs/1.0/characters
