### ISSUE TITLE
Add posibilty to play audio or execute macro

### ISSUE THREAD

**Issue by jonepatr** [eXaminator/kanka-foundry#60]
Hi! Would be really cool if it was possible to attach an ID to either an audio item or a macro, and have a button saying "execute" or something. 

Don't really have a specific usecase for the macro in mind, but for audio I have plenty of locations, and instead of creating a scene for a location, I use the plugin "Journal to canvas slideshow" which let's me show images from journal entries for the players. So it would be really nice to be able to quickly play a sound associated with that scene.

**Comment by eXaminator** [comment]
Thanks for writing this proposal.

Just so that I understand you correctly: You want to be able to somehow link(?) to a sound or macro in an entities entry(?) in Kanka and have the module create an "executable" link to that sound or macro?

To be honest, this seems like it should be its own module as it has nothing to do with Kanka and for me this would fee of out of place for this module.

The closest thing I have been thinking about before was to add a possibility to at least preview audio assets that were attached to an entity in Kanka, but even that doesn't seem too useful at the moment (as you can just open it in a new tab and play it there). So I **might** think about adding this feature and maybe allow the GM to play this sound for players too - but I haven't really given this any thought so I'm not even sure if it is feasible.

I try to not add special functionality that goes above and beyond what Kanka provides itself and I don't want to encourage people to add stuff to their entities in Kanka that is not usable in Kanka itself, because at that point what's even the advantage of having it in Kanka? What's the advantage of linking to some audio file that you can't even access from Kanka?

This is why I would rather see this as its own module that allows you to link to sounds / macros from journal entries. If that were the case, you could probably fabricate such a link in Kanka to have it work after syncing (but not in Kanka itself). But I don't really want this module to actively encourage this.

I'll leave this open for now, just to give you an opportunity to further convince me that this makes sense for this module. But right now I am sorry to say that I'm not convinced.

**Comment by jonepatr** [comment]
I completely agree with your reasoning. I just noticed this was something that i was missing, but it makes perfect sense. If I find some time during the summer I'll create a new module with such a functionality, and will let you know. But for now you can close this issue. Sorry for bothering!

**Comment by eXaminator** [comment]
No worries! I'm always happy about constructive issues, wether I accept them or not :)
