### ISSUE TITLE
Styling incompatibility with PF2e system

### ISSUE THREAD

**Issue by Asheboxx** [eXaminator/kanka-foundry#64]
Entries sync correctly but only main text is displayed without tabs/images/entity notes/links. Uses PF2e default styling or Foundry styling based on which setting is enabled.

Tested with Kanka as only active module on Foundry Version 0.8.8, PF2e Version 2.9.1

**Comment by eXaminator** [comment]
Have you updated to the latest version von Kanka-Foundry? That's actually the main bug that should have been fixed with the last release.

As a side note: There are currently talks about how to improve compatibility of modules and systems that change the behavior of JournalEntries. So we will hopefully se some better interoperability of different modules in this space in the future (this includes other modules like GM Screen etc. that don't work properly with Kanka-Foundry as of 2.3.1.

**Comment by Asheboxx** [comment]
This is with the latest version of Kanka (2.3.1)

**Comment by eXaminator** [comment]
Very strange. Please try and make sure there are no caching problems in your browser, because I think it **should** work. i will test this again (as soon as I find time).

That being said, I probably won't fix issues in this regard for now (unless it's a very easy fix) as I'd like to get a better grasp of what the final solution needs to be to improve interoperability with other modules / systems before I invest more time into this.

**Comment by Asheboxx** [comment]
The new latest Version of PF2e System (2.10.1.7007) does not seem to have this issue.

**Comment by eXaminator** [comment]
Thanks for letting me know!
