### ISSUE TITLE
Shim being loaded as a script is an issue

### ISSUE THREAD

**Issue by akrigline** [eXaminator/kanka-foundry#67]
I'm seeing `Not allowed to re-assign the global instance of libWrapper` while both this module and LibWrapper is installed. I confirmed with ruipin and this is because the libwrapper shim is expected to be used as an imported esmodule.

I'm guessing this is from the JE shim, which will be obsolete soon anyway?

**Comment by ruipin** [comment]
The problem is that [this file](https://github.com/eXaminator/kanka-foundry/blob/main/src/sheetClassShim.js#L75) is loaded as `scripts`, rather than `esmodules`. As such, it is running in global scope, and the `libWrapper` symbol it creates will be visible by every other module, even though it is not the full library.

While the shim will check for `libWrapper.is_fallback` before using it, many modules that do not use the shim might not, and as such this might actually cause modules to believe the library is installed when it is not.

In addition, if more than one module does this, it is unknown which module will run later and thus which module will "win out". As such, you cannot predict which implementation the shim has.

These reasons are why the libWrapper documentation states in bold:

> Please do not make your custom shim available in the global scope.

I would ask that you change this so that you `import` this file, rather than loading it in global scope as a script.

**Comment by eXaminator** [comment]
Thanks for letting me know, looking at the discord there seems to have been a bit of confusion around this issue in this regard.

Well, I didn't want to update this package to use the new (soon to be released) sheet registrar lib until I actually had a bug or feature to release with it... I guess I have a bug fix on my hands now ;)

I'll fix this as soon as I can, hopefully (but not quite guaranteed) sometime tonight (CEST).
