### ISSUE TITLE
Running this on FoundryVTT v7.10 ?

### ISSUE THREAD

**Issue by Sonny-Crockett** [eXaminator/kanka-foundry#76]
I am stuck on FVTT 7.10 due to my game system not being updated stable, looks like I cannot install this on local or forge due to the dependency being: ("minimumCoreVersion": "0.8.8"). I tried downloading Version 1.9.7 of this module but it linked to the same dependency. Any ideas?

I assume this is necessary for the module to function. Otherwise very excited to use this!

Thanks!

**Comment by eXaminator** [comment]
There have been many changes in this module. I have practically rewritten the module in 2.0.0, so all the screenshots and many features won't apply for pre-2.0.0 Versions.

I have just fixed the manifest of Version 1.9.7, so it should now work and install the correct version. That being said, I don't guarantee that this version still works, due to changes made in the Kanka API since then. But you can certainly try.

Sadly it's not feasible for me to ensure support for older foundry versions, especially since I have started using the Document Sheet Registrar library as a dependency, which probably isn't 0.7.10 compatible itself. So I wish I could help you more, but I guess it would make more sense to see if you can get the system dev to upgrade to 0.8.x, which they should do anyway if the system is supposed to have a future in foundry...

**Comment by Sonny-Crockett** [comment]
Thank you for the help. Yes my hope is we can move up to 0.8.x but the 1 of the 2 devs has left and the other is on hiatus so :( 

I will hopefully be using your up-to-date version sometime in the future.
