### ISSUE TITLE
Foundry Dynamic Entity Links are not clickable in Kanka Journal Entry in Foundry

### ISSUE THREAD

**Issue by anthonyscorrea** [eXaminator/kanka-foundry#80]
As a workaround for Kanka Journals not being Actor sheets, I wanted to add an attribute that has the Foundry Entity link (see:[https://foundryvtt.com/article/journal/#links](Dynamic Entity Links)). Unfortunately, it is not recognized in the Kanka sheet, it just shows the text and not a clickable link.

**Comment by eXaminator** [comment]
Thanks for opening this issue.

This is probably because this would be handled by Foundry on the backend side of things, which isn't possible for modules with custom data like this (though I'm not 100% sure).

I'll look into it next time I'm working on this and see if there is a way for me to allow this without adding my own special handling for this.
