### ISSUE TITLE
Kanka Interface loadEntity Error

### ISSUE THREAD

**Issue by moodster321** [eXaminator/kanka-foundry#81]
When I try to open the interface for kanka-foundry (clicking the kanka icon) the error "An error occurred while loading the list of entities from Kanka."

I can update entities that are already in my game, so I know the access token I have works. I did recently superboost my campaign though, so maybe that is an issue? I also noticed that kanka is using captchas more aggressively.

I looked for this in your code and it seems linked to 'loadEntity' which I think points to this being on kankas end. Let me know if you have any ideas about what the issue is, thanks!

**Comment by eXaminator** [comment]
Ok, with a hint from Jay from kanka, this issue is actually not related to the DDoS protection at all right now, but to the recent Kanka update. There is a bug in Kanka in regard to how paging works for long lists of entities (the links to the next page and others are broken). Jay is on it and it should be fixed soon I hope.
